name: Unit Test

on:
  push:
    branch: ["dev"]
  pull_request:
    branch: ["dev","master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Install dependencies
      run: dotnet restore src/
    
    - name: Download adb binaries.
      run: ./scripts/get_adb.ps1
      
    - name: Building with script
      run: ./scripts/build_canary.ps1

    - name: Unit Test
      run: dotnet test src/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Canary-Artifact
        path: AutumnBox-Canary # or path/to/artifact