name: Test

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out codes
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore src/
      
    - name: Clear binaries floder
      run: Remove-Item -Path adb_binary -Recurse -Force
      
    - name: Download adb binaries.
      run: git clone https://github.com/zsh2401/AutumnBox-AdbBinaries-Store.git adb_binary
      
    
    - name: Unit Test
      run: dotnet test src/AutumnBox.Tests --no-restore --verbosity normal
      
    - name: App Build Test
      run: dotnet build src/AutumnBox.DNCGUI --configuration Release --no-restore
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test-Artifact
        path: src/AutumnBox.DNCGUI/bin/Release/netcoreapp3.1/ # or path/to/artifact
